[[main]]
    name = "Home"
    identifier = "home"
    url = "/fr/"
    weight = 1
    
[[main]]
    name = "About"
    url = "#"
    identifier = "about-us"
    weight = 2
[[main]]
    name = "Mission"
    url = "/fr/about-us/mission/"
    weight = 1
    parent = "about-us"
[[main]]
    name = "Get involved"
    url = "/fr/about-us/involved/"
    weight = 2
    parent = "about-us"
[[main]]
    name = "Meet the global team"
    url = "/fr/about-us/global-team/"
    weight = 3
    parent = "about-us"
[[main]]
    name = "History"
    url = "/fr/about-us/history/"
    weight = 4
    parent = "about-us"

    
[[main]]
    name = "Directory"
    url = "/fr/directory/"
    weight = 3
    
[[main]]
    name = "Activities"
    identifier = "activities"
    url = "#"
    weight = 4
[[main]]
    name = "Events"
    url = "/fr/activities/events/"
    weight = 1
    parent = "activities"
[[main]]
    name = "Mentoring Program"
    url = "/fr/activities/mentoring/"
    weight = 3
    parent = "activities"
[[main]]
    name = "Rotating Twitter Curator"
    url = "/fr/activities/rocur/"
    weight = 4
    parent = "activities"
[[main]]
    name = "Abstract review"
    url = "/fr/activities/review/"
    identifier = "abstract-review"
    weight = 5
    parent = "activities"
[[main]]
    name = "International Women's Day Campaigns"
    url = "/fr/activities/iwd/"
    weight = 6
    parent = "activities"
[[main]]
    name = "Community Slack"
    url = "https://rladies-community-slack.herokuapp.com/"
    weight = 7
    parent = "activities"
[[main]]
    name = "Global dashboard"
    url = "https://benubah.github.io/r-community-explorer/rladies.html"
    weight = 8
    parent = "activities"

    
#[[main]]
#    name = "Blog"
#    url = "https://blog.rladies.org/"
#    weight = 5
    
[[main]]
    name = "Blog"
    url = "/fr/post"
    weight = 5
    