language: r
cache: packages
branches:
    only:
        - source
r_github_packages:
    - rstudio/blogdown
    - rladies/meetupr

before_script:
    - rm docs/events/index.html
    - Rscript -e 'blogdown::install_hugo(version = "0.20.7")'

script:
    - Rscript -e 'blogdown::build_site(TRUE)'

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: source
    local_dir: public
    target_branch: master